set_property SRC_FILE_INFO {cfile:D:/Dropbox/Rodgel/Projects/1402/Triangle-TeraHertz/Triangle_Terahertz_FPGA_Ver2/Triangle_Terahertz_FPGA_Ver2.srcs/constrs_1/imports/Triangle-TeraHertz/Cmod-S7-25-Master.xdc rfile:../../../Triangle_Terahertz_FPGA_Ver2.srcs/constrs_1/imports/Triangle-TeraHertz/Cmod-S7-25-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports LED]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M9 [get_ports clk_in]
