# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Other/Dropbox/Rodgel/Projects/Triangle-TeraHertz/Triangle_Terahertz_FPGA_Ver1/Triangle_Terahertz_FPGA_Ver1.srcs/sources_1/ip/div_gen_1/div_gen_1.xci
# IP: The module: 'div_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Other/Dropbox/Rodgel/Projects/Triangle-TeraHertz/Triangle_Terahertz_FPGA_Ver1/Triangle_Terahertz_FPGA_Ver1.srcs/sources_1/ip/div_gen_1/div_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Other/Dropbox/Rodgel/Projects/Triangle-TeraHertz/Triangle_Terahertz_FPGA_Ver1/Triangle_Terahertz_FPGA_Ver1.srcs/sources_1/ip/div_gen_1/div_gen_1.xci
# IP: The module: 'div_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Other/Dropbox/Rodgel/Projects/Triangle-TeraHertz/Triangle_Terahertz_FPGA_Ver1/Triangle_Terahertz_FPGA_Ver1.srcs/sources_1/ip/div_gen_1/div_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
